### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by chapterjason** [SymfonyTest/symfony-bundle-test#85]
Here are some of my thoughts on the next releases which already brings the Symfony 7 and PHP 8.3 Support in 3.x and some preparation in the 2.x branch which is missing, I will fix that the next days as follows:

## 2.1.0 (2.x)

- [x] Create 2.x branch from 0a83997b5e51ad26827f40ddef99ba72edf8052f
- [x] Backport some CI changes from f8260c01a005b6eec6129043127aef9d0c5784eb #87
- [x] Implement #77 ~~with compatibility layer~~ (compatibility layer was actually not required, we have our own method.) #88 
- [x] Rebase and merge #82
- [ ] Release 2.1.0

## 3.0.0 (master)

- [x] #89
- [x] Update README
- [x] ~~Remove compatibility layer from #77~~ Not required anymore
- [x] Release 3.0.0

WDYT?

// cc: @Nyholm

**Comment by chapterjason** [comment]
Hey @Nyholm, the workflow currently only runs on "master." To test everything properly, it'd be helpful if it also ran on the 2.x branch. I'd like to support 2.x for a bit. See #87

**Comment by mbabker** [comment]
3.0's been released so closing.
